spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/person_info?serverTimezone=UTC
    username: root
    password: ztt202812
    druid:
      druid:
        #初始化连接数
        initial-size: 1
        #最小空闲连接
        min-idle: 1
        #最大活动连接
        max-active: 20
        #获取连接时测试是否可用
        test-on-borrow: true
        #监控页面启动
        filter:
          wall:
            config:
              start-transaction-allow: true
  web:
    resources:
      static-locations: classpath:/static/

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  type-aliases-package: com.ztt.springboot.pojo

